/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.harvest;
@org.apache.avro.specific.AvroGenerated
public enum HarvestEventType implements org.apache.avro.generic.GenericEnumSymbol<HarvestEventType> {
  DATASOURCE_HARVEST_TRIGGER, DATASOURCE_HARVEST, DATASOURCE_RESOURCE_EXTRACTION, RESOURCE_HARVEST, RESOURCE_REMOVAL, RESOURCE_REASONING, RESOURCE_RDF_PARSING, RESOURCE_SEARCH_PROCESSING, RESOURCE_AI_SEARCH_PROCESSING, RESOURCE_API_PROCESSING, RESOURCE_SPARQL_PROCESSING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"HarvestEventType\",\"namespace\":\"no.fdk.harvest\",\"symbols\":[\"DATASOURCE_HARVEST_TRIGGER\",\"DATASOURCE_HARVEST\",\"DATASOURCE_RESOURCE_EXTRACTION\",\"RESOURCE_HARVEST\",\"RESOURCE_REMOVAL\",\"RESOURCE_REASONING\",\"RESOURCE_RDF_PARSING\",\"RESOURCE_SEARCH_PROCESSING\",\"RESOURCE_AI_SEARCH_PROCESSING\",\"RESOURCE_API_PROCESSING\",\"RESOURCE_SPARQL_PROCESSING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
