---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: fdk-harvest-admin-service
  labels:
    fdk.service: fdk-harvest-admin-service
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    fdk.service: fdk-harvest-admin-service
status:
  loadBalancer: {}
